In [1]:
import pandas as pd
from io import StringIO
from IPython.display import display

# --- Load Weather Data ---
with open("raw data weather text.txt", "r", encoding="utf-8") as f:
    weather_text = f.read()

weather_df = pd.read_csv(StringIO(weather_text))

# Clean weather data
weather_df['Date'] = pd.to_datetime(weather_df['datetime']).dt.date
weather_clean = weather_df[['Date', 'temp', 'humidity', 'windgust']].rename(
    columns={'temp': 'Temperature', 'humidity': 'Humidity', 'windgust': 'Windgust'}
)

# --- Load Traffic Data ---
traffic_df = pd.read_csv("traffic_announcement.csv", delimiter=';')
traffic_df['ANNOUNCEMENT_STARTING_DATETIME'] = pd.to_datetime(
    traffic_df['ANNOUNCEMENT_STARTING_DATETIME'], errors='coerce'
)
traffic_df['Date'] = traffic_df['ANNOUNCEMENT_STARTING_DATETIME'].dt.date

# Count accidents per day
accident_counts = traffic_df.groupby('Date').size().reset_index(name='Accident Count')

# --- Merge datasets ---
final_df = pd.merge(accident_counts, weather_clean, on='Date', how='inner')
final_df = final_df[['Date', 'Accident Count', 'Temperature', 'Windgust', 'Humidity']]

# --- Display final dataframe ---
display(final_df)

# --- Export to Excel ---
final_df.to_excel("final_numeric_weather_accidents.xlsx", index=False)
print("✅ Data exported to 'final_numeric_weather_accidents.xlsx'")

           Date  Accident Count  Temperature  Windgust  Humidity
0    2024-01-01              28         55.3      16.1      76.2
1    2024-01-02              39         54.4      23.0      84.3
2    2024-01-03              29         53.3      28.6      87.4
3    2024-01-04              44         56.1      28.0      81.3
4    2024-01-05              36         54.2      27.7      73.5
..          ...             ...          ...       ...       ...
361  2024-12-27              37         43.7      36.9      88.9
362  2024-12-28              31         44.4      33.6      87.6
363  2024-12-29              17         45.5      32.0      87.0
364  2024-12-30              48         43.7      25.5      86.7
365  2024-12-31              32         44.2      13.2      85.9

[366 rows x 5 columns]

✅ Data exported to 'final_numeric_weather_accidents.xlsx'